package Model.Enums;

public enum PermissionType {
    ADD_PLAYER,
    ADD_TEAM_MANAGER,
    ADD_COACH,
    ADD_COURT,
    ADD_FINANCIAL,
    CHANGE_STATUS,
    REMOVE_PLAYER,
    REMOVE_TEAM_MANAGER,
    REMOVE_COACH,
    REMOVE_COURT,
    OWNER,
    CREATE_NEW_TEAM
}
